version: "3.8"

services:
  office-iot:
    build: .
    container_name: office-iot-server
    env_file: .env
    restart: always
    ports:
      - "8878:8878"
      - "8877:8877"
    environment:
      - HOST=0.0.0.0
      - CONTROL_PORT=8878
      - STATUS_PORT=8877
      - UNLOCK_DURATION=10
      - DEBUG=false
    networks:
      - office-iot

networks:
  office-iot:
    driver: bridge
